// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA2oKqNJQLpCW82yOVK9353BrxFepLWbw',
    appId: '1:795572857509:web:51be2ed88a4529419e3b4c',
    messagingSenderId: '795572857509',
    projectId: 'notes-72bdc',
    authDomain: 'notes-72bdc.firebaseapp.com',
    storageBucket: 'notes-72bdc.firebasestorage.app',
    measurementId: 'G-3CBLECKJS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLa3SidzQ_LIgeRnLfdl6dCmYSGeDvOyY',
    appId: '1:795572857509:android:f4bd38e03497e6369e3b4c',
    messagingSenderId: '795572857509',
    projectId: 'notes-72bdc',
    storageBucket: 'notes-72bdc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs31glAEzLZoA4eY-YkP-Qr3-IiqipXc0',
    appId: '1:795572857509:ios:a3d368ad366606bf9e3b4c',
    messagingSenderId: '795572857509',
    projectId: 'notes-72bdc',
    storageBucket: 'notes-72bdc.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs31glAEzLZoA4eY-YkP-Qr3-IiqipXc0',
    appId: '1:795572857509:ios:a3d368ad366606bf9e3b4c',
    messagingSenderId: '795572857509',
    projectId: 'notes-72bdc',
    storageBucket: 'notes-72bdc.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDA2oKqNJQLpCW82yOVK9353BrxFepLWbw',
    appId: '1:795572857509:web:d7744b34b48fee759e3b4c',
    messagingSenderId: '795572857509',
    projectId: 'notes-72bdc',
    authDomain: 'notes-72bdc.firebaseapp.com',
    storageBucket: 'notes-72bdc.firebasestorage.app',
    measurementId: 'G-XTBPB9W0VD',
  );
}
