// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE30x2Yc9GuZXARPHj0FegyE89byHQ_xI',
    appId: '1:105566104201:web:80b97054e51e7044157458',
    messagingSenderId: '105566104201',
    projectId: 'daftarbelanja-5303d',
    authDomain: 'daftarbelanja-5303d.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-5303d-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-5303d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHEtpOxl2ARXQ_ATBC2q03o3tJNzmBOjA',
    appId: '1:105566104201:android:cbf03e815da42dbf157458',
    messagingSenderId: '105566104201',
    projectId: 'daftarbelanja-5303d',
    databaseURL: 'https://daftarbelanja-5303d-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-5303d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_3PWkzxmgHT0ekqZbVh0X7lU5o_ZBpMk',
    appId: '1:105566104201:ios:289eafb859ed68e1157458',
    messagingSenderId: '105566104201',
    projectId: 'daftarbelanja-5303d',
    databaseURL: 'https://daftarbelanja-5303d-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-5303d.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_3PWkzxmgHT0ekqZbVh0X7lU5o_ZBpMk',
    appId: '1:105566104201:ios:289eafb859ed68e1157458',
    messagingSenderId: '105566104201',
    projectId: 'daftarbelanja-5303d',
    databaseURL: 'https://daftarbelanja-5303d-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-5303d.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE30x2Yc9GuZXARPHj0FegyE89byHQ_xI',
    appId: '1:105566104201:web:f852e9ddc923a48c157458',
    messagingSenderId: '105566104201',
    projectId: 'daftarbelanja-5303d',
    authDomain: 'daftarbelanja-5303d.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-5303d-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-5303d.firebasestorage.app',
  );
}
