// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgl5h3DAtELqTGXor8w073gYd3ZixjuhI',
    appId: '1:787489771463:web:a27610945192a9ee7e93e2',
    messagingSenderId: '787489771463',
    projectId: 'cloud-message-abb25',
    authDomain: 'cloud-message-abb25.firebaseapp.com',
    storageBucket: 'cloud-message-abb25.firebasestorage.app',
    measurementId: 'G-K3T7086FX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmmXXP3V--GvtXUIaz84d9W7E-Y-kbI24',
    appId: '1:787489771463:android:20dedb5539dd5da37e93e2',
    messagingSenderId: '787489771463',
    projectId: 'cloud-message-abb25',
    storageBucket: 'cloud-message-abb25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnCTI7TBI4uYC0NxOJ_tt4-j-oTeS7Yck',
    appId: '1:787489771463:ios:dd0fc1ffd50c246b7e93e2',
    messagingSenderId: '787489771463',
    projectId: 'cloud-message-abb25',
    storageBucket: 'cloud-message-abb25.firebasestorage.app',
    iosBundleId: 'com.example.cloudMessage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnCTI7TBI4uYC0NxOJ_tt4-j-oTeS7Yck',
    appId: '1:787489771463:ios:dd0fc1ffd50c246b7e93e2',
    messagingSenderId: '787489771463',
    projectId: 'cloud-message-abb25',
    storageBucket: 'cloud-message-abb25.firebasestorage.app',
    iosBundleId: 'com.example.cloudMessage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgl5h3DAtELqTGXor8w073gYd3ZixjuhI',
    appId: '1:787489771463:web:dd7704ba9de100f07e93e2',
    messagingSenderId: '787489771463',
    projectId: 'cloud-message-abb25',
    authDomain: 'cloud-message-abb25.firebaseapp.com',
    storageBucket: 'cloud-message-abb25.firebasestorage.app',
    measurementId: 'G-G37YF0XVWL',
  );

}