// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDBY-3vYdfScTQYyPeKjiignWjITmMa_w',
    appId: '1:17677630169:web:7cee1d1cc96529e6921cc8',
    messagingSenderId: '17677630169',
    projectId: 'mdpgold-bb763',
    authDomain: 'mdpgold-bb763.firebaseapp.com',
    databaseURL: 'https://mdpgold-bb763-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-bb763.firebasestorage.app',
    measurementId: 'G-YBDKX8DJBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfXh7206BJTRO94JF_eUK1eaCGtJm77hw',
    appId: '1:17677630169:android:d7d65d2c32afb719921cc8',
    messagingSenderId: '17677630169',
    projectId: 'mdpgold-bb763',
    databaseURL: 'https://mdpgold-bb763-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-bb763.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtesQK8dwpqAiNh6tOCPK89Bv01Uzic88',
    appId: '1:17677630169:ios:eefb488172c93c5d921cc8',
    messagingSenderId: '17677630169',
    projectId: 'mdpgold-bb763',
    databaseURL: 'https://mdpgold-bb763-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-bb763.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtesQK8dwpqAiNh6tOCPK89Bv01Uzic88',
    appId: '1:17677630169:ios:eefb488172c93c5d921cc8',
    messagingSenderId: '17677630169',
    projectId: 'mdpgold-bb763',
    databaseURL: 'https://mdpgold-bb763-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-bb763.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDBY-3vYdfScTQYyPeKjiignWjITmMa_w',
    appId: '1:17677630169:web:df1e396857122414921cc8',
    messagingSenderId: '17677630169',
    projectId: 'mdpgold-bb763',
    authDomain: 'mdpgold-bb763.firebaseapp.com',
    databaseURL: 'https://mdpgold-bb763-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-bb763.firebasestorage.app',
    measurementId: 'G-W9BDSF61JV',
  );

}